import React, { useState } from 'react';
import { Camera, ChevronRight, Check, X, Plus } from 'lucide-react';
import { FormField } from '../components/ui/FormField';
import { useBatches } from '../hooks/useBatches'; 

interface BatchItem {
  id: string;
  date: string;
  count: string;
  status: 'Completed' | 'Incomplete';
}

interface CreateBatchPageProps {
  onNavigateToUpload: (batchData: any) => void;
}

export const CreateBatchPage = ({ onNavigateToUpload }: CreateBatchPageProps) => {
  const { createBatch, loading, batches } = useBatches(); 

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault(); 
    
    const formData = new FormData(e.currentTarget);
    
    const payload = {
      jenis: formData.get('jenisIkan') as string,
      lokasi: formData.get('lokasi') as string,
      estimasi_jumlah: Number(formData.get('estimasiJumlah')),
      berat_total: Number(formData.get('beratTotal')),
      catatan: (formData.get('catatan') as string) || ""
    };
    
    try {
      const newBatch = await createBatch(payload);
      onNavigateToUpload({ batchId: newBatch.id }); 
    } catch (error) {
      console.error("Gagal membuat batch:", error);
      alert("Terjadi kesalahan saat membuat batch. Coba lagi.");
    }
  };

  return (
    <div className="flex-1 bg-white min-h-screen p-8 max-w-6xl mx-auto">
      <div className="flex items-center text-sm text-gray-500 mb-2">
        <span className="hover:text-gray-800 cursor-pointer">Batches</span>
        <ChevronRight size={14} className="mx-1" />
        <span className="text-gray-900 font-medium">Create batch</span>
      </div>

      <h1 className="text-3xl font-bold text-gray-900 mb-8">Buat batch baru</h1>

      <div className="flex flex-col lg:flex-row gap-8 items-start">
        <form 
          onSubmit={handleSubmit} 
          className="flex-1 bg-white border border-gray-200 rounded-2xl p-6 shadow-sm w-full"
        >
          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6">
            <FormField 
              label="Batch ID" 
              name="batchId"
              defaultValue="Auto-generated by System" 
              subtext="Akan dibuat otomatis setelah disubmit" 
              readOnly 
            />
            
            <FormField 
              label="Lokasi Pengambilan" 
              name="lokasi"
              placeholder="Masukkan lokasi..."
              required 
            />
            
            <FormField 
              label="Jenis Ikan" 
              name="jenisIkan"
              isSelect 
              options={['', 'Kakap merah', 'Tuna', 'Kerapu', 'Bawal']} 
              required 
            />
            
            <FormField 
              label="Estimasi Jumlah" 
              name="estimasiJumlah"
              type="number"
              placeholder="0"
              min="1"
              suffix="ekor" 
              required 
            />
            
            <FormField 
              label="Berat Total" 
              name="beratTotal"
              type="number"
              step="0.01"
              placeholder="0.0"
              min="0.1"
              suffix="kg" 
              required 
            />
          </div>

          <div className="mt-2">
            <FormField 
              label="Catatan" 
              name="catatan"
              type="textarea" 
              placeholder="Tambahkan catatan (opsional)..."
            />
          </div>

          <div className="bg-orange-50 rounded-xl p-4 flex items-start gap-3 mt-4 mb-8">
            <div className="bg-orange-500 text-white p-2 rounded-lg shrink-0 mt-0.5">
              <Camera size={20} />
            </div>
            <div>
              <h4 className="text-orange-700 font-bold text-sm">Setelah batch dibuat</h4>
              <p className="text-orange-600/80 text-sm mt-0.5">
                Anda akan diarahkan ke layar pengambilan gambar untuk meng-upload foto ikan satu per satu.
              </p>
            </div>
          </div>

          <div className="flex justify-end gap-3 pt-4 border-t border-gray-100">
            <button 
              type="button" 
              className="px-5 py-2.5 text-sm font-semibold text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Batal
            </button>
            
            <button 
              type="submit"
              disabled={loading}
              className={`px-5 py-2.5 text-sm font-semibold text-white rounded-lg transition-colors flex items-center gap-1
                ${loading ? 'bg-orange-300 cursor-not-allowed' : 'bg-[#f47d31] hover:bg-[#e06a20]'}
              `}
            >
              {loading ? 'Menyimpan...' : (
                <>Buat batch & lanjut <Plus size={16} /></>
              )}
            </button>
          </div>
        </form>

        {/* KOLOM KANAN: BATCH TERAKHIR */}
        <div className="w-full lg:w-[320px]">
          <h3 className="text-xs font-bold text-gray-500 uppercase tracking-wide mb-4">
            Batch Terakhir
          </h3>
          <div className="flex flex-col gap-3">
            {batches.map((batch: any, idx: number) => (
              <div 
                key={idx} 
                onClick={() => batch.status === 'Incomplete' ? onNavigateToUpload({ batchId: batch.id }) : null}
                className={`bg-white border border-gray-200 rounded-xl p-4 flex items-center justify-between transition-colors shadow-sm ${batch.status === 'Incomplete' ? 'hover:border-orange-400 cursor-pointer' : 'cursor-default'}`}
              >
                <div>
                  <h4 className="text-sm font-bold text-gray-900 mb-0.5">{batch.id}</h4>
                  <p className="text-[13px] text-gray-500">{batch.date} • {batch.count} ikan</p>
                </div>
                <div className="flex items-center gap-3">
                  {batch.status === 'Completed' ? (
                    <span className="flex items-center gap-1 bg-green-100 text-green-700 px-2 py-1 rounded-md text-[11px] font-semibold"><Check size={12} /> Completed</span>
                  ) : (
                    <span className="flex items-center gap-1 bg-red-100 text-red-600 px-2 py-1 rounded-md text-[11px] font-semibold"><X size={12} /> Incomplete</span>
                  )}
                  <ChevronRight size={16} className="text-gray-400" />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};